# Generated by Django 2.2.10 on 2021-08-16 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Poll',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='название')),
                ('start_date', models.DateField(auto_now_add=True, verbose_name='дата старта')),
                ('end_date', models.DateField(verbose_name='дата окончания')),
                ('description', models.TextField(blank=True, null=True, verbose_name='описание')),
            ],
            options={
                'verbose_name': 'опрос',
                'verbose_name_plural': 'опросы',
                'ordering': ('-start_date',),
            },
        ),
    ]
