# Generated by Django 2.2.10 on 2021-08-17 08:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_question'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poll',
            name='name',
            field=models.CharField(db_index=True, max_length=200, unique=True, verbose_name='название'),
        ),
        migrations.AlterField(
            model_name='question',
            name='text',
            field=models.TextField(db_index=True, verbose_name='текст вопроса'),
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.TextField(verbose_name='ответ')),
                ('question', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='polls.Question', verbose_name='вопрос')),
            ],
        ),
    ]
