# Generated by Django 2.2.10 on 2021-08-18 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0005_auto_20210818_1022'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poll',
            name='end_date',
            field=models.DateField(blank=True, null=True, verbose_name='дата окончания'),
        ),
    ]
